# -*- coding: utf-8 -*-
"""DevTown_assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9Cy3lG84OgzgMxxgWg41XlOf4UAWBIv
"""

import kagglehub
import pandas as pd
import numpy as np

path = kagglehub.dataset_download("lava18/google-play-store-apps")

print("Path to dataset files:", path)

data=pd.read_csv(path + '/googleplaystore.csv')
print("Dataset Loaded Properly")

print("shape: ",data.shape)

data.head()

data.info()

data.describe()

print("Unique data :",data['Category'].nunique())
print("Sample data : ",data['Category'].unique()[:100])

print("Duplicate Rows : ",data.duplicated().sum())

data.isnull().sum()

data.drop_duplicates(inplace=True)
print("Duplicate Rows : ",data.duplicated().sum())
print("New shape is : ",data.shape)

data.isnull().sum()

data['Rating'].fillna(data['Rating'].mean(),inplace=True)

data.drop_duplicates(inplace=True)
print("Duplicate Rows removed , new shape is :",data.shape)

# data=pd.read_csv('cleaned_playstore.csv')

data['Price']=data['Price'].astype(str).str.strip()
data['Installs']=data['Installs'].astype(str).str.strip()
data['Reviews']=data['Reviews'].astype(str).str.strip()


data['Price']=data['Price'].str.replace('$',"",regex=False)
data['Price']=pd.to_numeric(data['Price'],errors='coerce')

data['Installs']=data['Installs'].str.replace('+',"",regex=False)
data['Installs']=data['Installs'].str.replace(',',"",regex=False)
data['Installs']=pd.to_numeric(data['Installs'],errors='coerce')

data['Reviews']=pd.to_numeric(data['Reviews'],errors='coerce')

data.dropna(subset=['Price','Installs','Reviews'],inplace=True)

print("Data Type Cleaning Done")
data[['App','Price','Installs','Reviews']].head()

data.describe()

data=data[data['Rating']<=5]

data['isPaid']=data['Type'].apply(lambda x:1 if x=='Paid' else 0)
data[['App','Type','isPaid']].head()

data.to_csv('cleaned_playstore.csv',index=False)
print("Cleaned Dataset Saved as cleaned_playstore.csv")

"""**DAY 2**

"""

import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('cleaned_playstore.csv')

sns.set(style="whitegrid")

print("Shape:",data.shape)

data.head()

print(data.info())

print("\n Missing Values:\n",data.isnull().sum())

data.describe()

top_categories=data['Category'].value_counts().head(10)
print("Top 10 Categories:\n",top_categories)


plt.figure(figsize=(10,6))
sns.barplot(x=top_categories.values,y=top_categories.index,palette='viridis')
plt.title('Top 10 Categories')
plt.xlabel('Number of Apps')
plt.ylabel('Category')
plt.show()

avg_rating=data.groupby('Category')['Rating'].mean().sort_values(ascending=False).head(10)
print("Average Ratings by Category:\n",avg_rating)

plt.figure(figsize=(10,6))
sns.barplot(x=avg_rating.values,y=avg_rating.index,palette='viridis')
plt.title('Average Ratings by Category')
plt.xlabel('Average Rating')
plt.ylabel('Category')
plt.show()

print(sns.palettes.SEABORN_PALETTES.keys())

app_types=data['Type'].value_counts()
print("App Types:\n",app_types)

plt.figure(figsize=(8,6))
sns.barplot(x=app_types.index,y=app_types.values, palette='bright', hue=app_types.index, legend=False)
plt.title('Free vs Paid app Distribution')
plt.xlabel('Number of Apps')
plt.ylabel('Type')
plt.show()

plt.figure(figsize=(10,6))
sns.histplot(data['Rating'],bins=20,kde=True,color='orange')
plt.title('App Distribution of Ratings')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='Price',y='Rating',data=data,alpha=0.6,color='red')
plt.title('Price vs Rating')
plt.xlabel('Price')
plt.ylabel('Rating')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(y='Installs',x='Rating',data=data,alpha=0.6,color='orange',hue='Type')
plt.xscale('log')
plt.yscale('log')
plt.title('Installs vs Rating(log scale)')
plt.xlabel('Rating')
plt.ylabel('Installs')
plt.legend(title='AppType')
plt.show()

corr=data[['Rating','Reviews','Installs','Price','isPaid']].corr()
print("Correlation Matrix:\n",corr)

plt.figure(figsize=(8,6))
sns.heatmap(corr,annot=True,cmap='coolwarm',linewidths=0.5,fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

data.describe().to_csv('eda_summary.csv')
print("EDA Summary Saved as eda_summary.csv")